---
- name: Instalação nginx
  apt:
    name: nginx
    state: latest

- name: Copia novo index.html
  copy:
    src: /home/igor/projects/ansible/Setup_Linux/ansible/files/index.html
    dest: /var/www/html/index.nginx-debian.html

- name: Iniciar serviço
  systemd:
    name: nginx
    state: started
    enabled: yes