---
- name: Atualização do sistema e pacotes
  apt:
    # upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Instalação de dependências
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
